locale                   : "Singapore"
title                    : "Liu Zhaoyu"
title_separator          : "-"
name                     : &name "Liu Zhaoyu"
description              : &description "CS PhD at NUS"
url                      : https://liuzyandy.github.io
baseurl                  : ""
repository               : "liuzyandy.github.io"
teaser                   : 
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false 
comments:
  provider               : false

atom_feed:
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
og_image                 :

# Social Profiles
social:
  type                   : "Person"
  name                   : "Liu Zhaoyu"
  links:
    - "https://github.com/LZYAndy"
    - "https://scholar.google.com/citations?user=oAl6cMIAAAAJ&hl"
    - "https://www.linkedin.com/in/zhaoyu-liu-960ab4179/"

# Analytics
analytics:
  provider               : false

# Site Author
author:
  name             : "Liu Zhaoyu"
  avatar           : "profile.png"
  bio              : "CS PhD at NUS"
  location         : "Singapore"
  github           : "LZYAndy"
  googlescholar    : "https://scholar.google.com/citations?user=oAl6cMIAAAAJ&hl"
  linkedin         : "https://www.linkedin.com/in/zhaoyu-liu-960ab4179/"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Timezone
timezone: Asia/Singapore

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
